In [3]:
import numpy as np
import pandas as pd

#### Creating a DataFrame
A DataFrame can be created using two Data structures that are - 1. List and 2. Dictionary

In [4]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}
# Dataframe is a two-dimensional, tabular data structure with labeled rows and columns. Also when we combine multiple Series then it becomes a Dataframe.
pd.DataFrame(data)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [5]:
data = [
    ["Alice", "Bob", "Charlie"],
    [25, 30, 35],
    ["New York", "London", "Paris"]
]
pd.DataFrame(data) # In this dataframe there is no header names like name age location, but we can that columns let's see in the below example

          0       1        2
0     Alice     Bob  Charlie
1        25      30       35
2  New York  London    Paris

In [6]:
col = ['Name', 'Age', 'City']
df = pd.DataFrame(data,columns=col) # By creating a separate header we can add into the Dataframe
df

       Name     Age     City
0     Alice     Bob  Charlie
1        25      30       35
2  New York  London    Paris

#### Selection and Indexing of Columns

In [7]:
# For targeting our columns or headers we use column names and you can use multiple names together

In [8]:
df

       Name     Age     City
0     Alice     Bob  Charlie
1        25      30       35
2  New York  London    Paris

In [9]:
df['Name']

0       Alice
1          25
2    New York
Name: Name, dtype: object

In [10]:
df[['Name','City']]

       Name     City
0     Alice  Charlie
1        25       35
2  New York    Paris

#### Creating a new column

In [11]:
df['Designation'] = ["Doctor", 'Engineer','MBBS'] 
df # We can create a new header

       Name     Age     City Designation
0     Alice     Bob  Charlie      Doctor
1        25      30       35    Engineer
2  New York  London    Paris        MBBS

#### Removing Columns

In [12]:
df.drop('Designation', axis=1) #  Removes the 'Designation' column from the dataframe. axis=1 is used bcz 1 is for columns(Headers) and 0 is for rows. Drop function uses axis=0 by default.

       Name     Age     City
0     Alice     Bob  Charlie
1        25      30       35
2  New York  London    Paris

In [13]:
df # Here we can see that the dataframe still have the column designation it's bcz of we did'nt used the inplace params we have to give inplace=True then only the column will be deleted permanently from the dataframe.

       Name     Age     City Designation
0     Alice     Bob  Charlie      Doctor
1        25      30       35    Engineer
2  New York  London    Paris        MBBS

In [14]:
df.drop('Designation', axis=1, inplace=True) # This inplace true will delete the column permanently.

In [15]:
df

       Name     Age     City
0     Alice     Bob  Charlie
1        25      30       35
2  New York  London    Paris

#### Removing Rows

In [16]:
df.drop(0)

       Name     Age   City
1        25      30     35
2  New York  London  Paris

#### Selection Rows

In [17]:
data2 = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Department': ['IT', 'HR', 'IT', 'Sales', 'Sales'],
    'Age': [28, 34, 41, 29, 32],
    'Salary': [75000, 65000, 90000, 60000, 70000],
    'Years_Exp': [3, 7, 12, 4, 6],
    'Remote': [True, False, True, False, True]
}
df2 = pd.DataFrame(data2)
df2

  Employee Department  Age  Salary  Years_Exp  Remote
0    Alice         IT   28   75000          3    True
1      Bob         HR   34   65000          7   False
2  Charlie         IT   41   90000         12    True
3    David      Sales   29   60000          4   False
4      Eva      Sales   32   70000          6    True

In [18]:
# To select our rows we will use the loc[3], It will give the whole row of index 3

In [19]:
df2.loc[2]

Employee      Charlie
Department         IT
Age                41
Salary          90000
Years_Exp          12
Remote           True
Name: 2, dtype: object

In [20]:
df2.loc[[1,2,3]] # We can also select multiple rows by providing multiple index

  Employee Department  Age  Salary  Years_Exp  Remote
1      Bob         HR   34   65000          7   False
2  Charlie         IT   41   90000         12    True
3    David      Sales   29   60000          4   False

In [21]:
df2.iloc[1]

Employee        Bob
Department       HR
Age              34
Salary        65000
Years_Exp         7
Remote        False
Name: 1, dtype: object

#### Selection Subsets of Rows and Columns

In [22]:
# To get a subset of a dataframe we use same rule like numpy. first we will pass the row index and then column header.

In [24]:
df2.loc[[0,3]][['Age', 'Remote']]

   Age  Remote
0   28    True
3   29   False

#### Conditional Selection

In [25]:
df2

  Employee Department  Age  Salary  Years_Exp  Remote
0    Alice         IT   28   75000          3    True
1      Bob         HR   34   65000          7   False
2  Charlie         IT   41   90000         12    True
3    David      Sales   29   60000          4   False
4      Eva      Sales   32   70000          6    True

In [28]:
df2[df2['Age'] > 30] # Filter DataFrame to show only rows where Age column is greater than 30. Here we uses same rules like we used in Numpy

  Employee Department  Age  Salary  Years_Exp  Remote
1      Bob         HR   34   65000          7   False
2  Charlie         IT   41   90000         12    True
4      Eva      Sales   32   70000          6    True

In [30]:
df2[(df2['Age'] > 30 ) & (df2['Remote'] == True)] # Multiple conditions

  Employee Department  Age  Salary  Years_Exp  Remote
2  Charlie         IT   41   90000         12    True
4      Eva      Sales   32   70000          6    True