In [2]:
import numpy as np
import pandas as pd

#### Finding Missing Data

In [5]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [18]:
df.isna() # isna() function is used to find the missing values from a Dataframe

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [19]:
df.isna().sum() # Sums the total no. of null values in each column

A    1
B    0
C    2
D    3
dtype: int64

In [20]:
df.isna().any() # Tells which column have null values. If a column have True then there is no null values

A     True
B    False
C     True
D     True
dtype: bool

#### Removing Missing Data

In [24]:
df.dropna() # Drops all the values row wise

     A  B    C    D
0  1.0  1  1.0  1.0

In [25]:
df.dropna(thresh=3) #  Remove rows that have fewer than 3 non-null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling the Missing Data

In [26]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.fillna(0) # Replace all NaN/null values in the DataFrame with 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [32]:
val = {'A':100,'B':200,'C':300,'D':400} 
df.fillna(value=val)  # Fill NaN values in each column with corresponding values from the dictionary. Filling is done by column wise

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0